name: biostitch
channels:
    - conda-forge
dependencies:
    - python >=3.6,<4
    - pip
    - numpy >= 1.17
    - pandas >= 0.25
    - dask >= 2.6.0
    - pip:
        - imagecodecs-lite
        - tifffile >= 2019.7.26
        - opencv-contrib-python >= 4.0
        
